# Generated by Django 4.2.30 on 2026-04-29 21:11

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('full_name', models.CharField(max_length=180, verbose_name='Nombre completo')),
                ('identification', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Teléfono')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/photos/', verbose_name='Foto')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nombre')),
                ('election_date', models.DateField(blank=True, null=True, verbose_name='Fecha de elección')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Elección',
                'verbose_name_plural': 'Elecciones',
                'ordering': ['-election_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nombre')),
                ('acronym', models.CharField(blank=True, max_length=16, verbose_name='Siglas')),
                ('list_number', models.CharField(blank=True, max_length=8, verbose_name='Número de lista')),
                ('color', models.CharField(blank=True, help_text='Hex #RRGGBB', max_length=7, verbose_name='Color')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='movements/logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Movimiento político',
                'verbose_name_plural': 'Movimientos políticos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Cargo')),
                ('scope', models.CharField(blank=True, choices=[('nacional', 'Nacional'), ('provincial', 'Provincial'), ('cantonal', 'Cantonal'), ('parroquial', 'Parroquial')], max_length=32, verbose_name='Ámbito')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'Anulada'), (1, 'Borrador'), (2, 'Activa'), (3, 'En pausa'), (4, 'Cerrada')], default=1, protected=True, verbose_name='Estado')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.candidate', verbose_name='Candidato')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.election', verbose_name='Elección')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.politicalmovement', verbose_name='Movimiento')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.position', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Campaña electoral',
                'verbose_name_plural': 'Campañas electorales',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('election', 'candidate', 'position'), name='campaigns_unique_election_candidate_position'),
        ),
    ]
