# Generated by Django 4.2.30 on 2026-05-08 20:15

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalmovement',
            name='color',
            field=core.fields.ColorField(blank=True, help_text='Hex #RRGGBB', max_length=7, verbose_name='Color'),
        ),
    ]
