# Generated by Django 4.2.30 on 2026-04-29 21:15

import apps.campaigns.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Anulada'), (1, 'Borrador'), (2, 'Activa'), (3, 'Cerrada')], default=apps.campaigns.workflows.CampaignWorkflow.Choices['DRAFT'], protected=True, verbose_name='Estado'),
        ),
    ]
