# Generated by Django 4.2.30 on 2026-05-06 18:00

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=core.fields.CompressedImageField(blank=True, null=True, upload_to='candidates/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='politicalmovement',
            name='logo',
            field=core.fields.CompressedImageField(blank=True, null=True, upload_to='movements/logos/', verbose_name='Logo'),
        ),
    ]
