# Generated by Django 4.2.30 on 2026-05-08 20:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_politicalmovement_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_date',
            field=models.DateField(blank=True, null=True, validators=[core.validators.reasonable_future_date_validator], verbose_name='Fecha de elección'),
        ),
    ]
