# Generated by Django 4.2.30 on 2026-05-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_election_election_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Cuando hay más de una campaña, esta es la que el sistema carga automáticamente al iniciar sesión. Solo una campaña puede estar marcada como predeterminada a la vez.', verbose_name='Predeterminada'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='campaigns_unique_default'),
        ),
    ]
