# Generated by Django 4.2.30 on 2026-05-07 17:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='map_center_latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('-2.304600'), max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud centro del mapa'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='map_center_longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('-78.117500'), max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud centro del mapa'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='map_default_zoom',
            field=models.PositiveSmallIntegerField(default=13, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Zoom inicial'),
        ),
    ]
