# Generated by Django 4.2.30 on 2026-05-06 18:00

import apps.tenancy.models
import core.fields
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_tenantsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbranding',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=core.storage.PublicFileSystemStorage(), upload_to=apps.tenancy.models.tenant_favicon_upload_to, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='tenantbranding',
            name='logo',
            field=core.fields.CompressedImageField(blank=True, null=True, storage=core.storage.PublicFileSystemStorage(), upload_to=apps.tenancy.models.tenant_logo_upload_to, verbose_name='Logo'),
        ),
    ]
