# Generated by Django 4.2.30 on 2026-05-08 20:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_tenantsettings_map_center_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsettings',
            name='map_center_latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('-2.304600'), max_digits=9, validators=[django.core.validators.MinValueValidator(-90, message='La latitud debe estar entre -90 y 90.'), django.core.validators.MaxValueValidator(90, message='La latitud debe estar entre -90 y 90.')], verbose_name='Latitud centro del mapa'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='map_center_longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('-78.117500'), max_digits=9, validators=[django.core.validators.MinValueValidator(-180, message='La longitud debe estar entre -180 y 180.'), django.core.validators.MaxValueValidator(180, message='La longitud debe estar entre -180 y 180.')], verbose_name='Longitud centro del mapa'),
        ),
    ]
