# Generated by Codex on 2026-05-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0002_alter_campaign_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliticalAgendaRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación")),
                ("created_user", models.CharField(editable=False, max_length=128, null=True, verbose_name="creado por")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="última fecha de modificación")),
                ("modified_user", models.CharField(editable=False, max_length=128, null=True, verbose_name="modificado por")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("title", models.CharField(max_length=180, verbose_name="Título")),
                ("event_type", models.CharField(choices=[("REUNION", "Reunión"), ("VISITA", "Visita"), ("RECORRIDO", "Recorrido"), ("MITIN", "Mitin"), ("ENTREVISTA", "Entrevista"), ("RUEDA_PRENSA", "Rueda de prensa"), ("OTRO", "Otro")], default="REUNION", max_length=20, verbose_name="Tipo")),
                ("status", models.CharField(choices=[("PENDIENTE", "Pendiente"), ("EN_REVISION", "En revisión"), ("APROBADA", "Aprobada"), ("RECHAZADA", "Rechazada"), ("CANCELADA", "Cancelada")], default="PENDIENTE", max_length=20, verbose_name="Estado")),
                ("priority", models.CharField(choices=[("BAJA", "Baja"), ("MEDIA", "Media"), ("ALTA", "Alta"), ("URGENTE", "Urgente")], default="MEDIA", max_length=12, verbose_name="Prioridad")),
                ("requester_name", models.CharField(max_length=180, verbose_name="Solicitante")),
                ("requester_phone", models.CharField(blank=True, max_length=32, verbose_name="Teléfono solicitante")),
                ("requester_email", models.EmailField(blank=True, max_length=254, verbose_name="Correo solicitante")),
                ("organization", models.CharField(blank=True, max_length=180, verbose_name="Organización / sector")),
                ("proposed_start_at", models.DateTimeField(blank=True, null=True, verbose_name="Inicio tentativo")),
                ("proposed_end_at", models.DateTimeField(blank=True, null=True, verbose_name="Fin tentativo")),
                ("alternative_dates", models.TextField(blank=True, verbose_name="Fechas alternativas")),
                ("province", models.CharField(blank=True, max_length=80, verbose_name="Provincia")),
                ("canton", models.CharField(blank=True, max_length=80, verbose_name="Cantón")),
                ("parish", models.CharField(blank=True, max_length=80, verbose_name="Parroquia")),
                ("sector", models.CharField(blank=True, max_length=120, verbose_name="Sector / barrio")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="Dirección")),
                ("reference", models.CharField(blank=True, max_length=255, verbose_name="Referencia")),
                ("objective", models.TextField(blank=True, verbose_name="Objetivo")),
                ("expected_attendees", models.PositiveIntegerField(default=0, verbose_name="Asistentes esperados")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Fecha de revisión")),
                ("rejection_reason", models.TextField(blank=True, verbose_name="Motivo de rechazo")),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agenda_requests", to="campaigns.campaign", verbose_name="Campaña")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_agenda_requests", to=settings.AUTH_USER_MODEL, verbose_name="Creado por")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_agenda_requests", to=settings.AUTH_USER_MODEL, verbose_name="Revisado por")),
            ],
            options={
                "verbose_name": "Solicitud de agenda política",
                "verbose_name_plural": "Solicitudes de agenda política",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="PoliticalAgendaEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación")),
                ("created_user", models.CharField(editable=False, max_length=128, null=True, verbose_name="creado por")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="última fecha de modificación")),
                ("modified_user", models.CharField(editable=False, max_length=128, null=True, verbose_name="modificado por")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("title", models.CharField(max_length=180, verbose_name="Título")),
                ("event_type", models.CharField(choices=[("REUNION", "Reunión"), ("VISITA", "Visita"), ("RECORRIDO", "Recorrido"), ("MITIN", "Mitin"), ("ENTREVISTA", "Entrevista"), ("RUEDA_PRENSA", "Rueda de prensa"), ("OTRO", "Otro")], default="REUNION", max_length=20, verbose_name="Tipo")),
                ("status", models.CharField(choices=[("BORRADOR", "Borrador"), ("AGENDADO", "Agendado"), ("REPROGRAMADO", "Reprogramado"), ("CANCELADO", "Cancelado"), ("REALIZADO", "Realizado")], default="BORRADOR", max_length=20, verbose_name="Estado")),
                ("start_at", models.DateTimeField(verbose_name="Inicio")),
                ("end_at", models.DateTimeField(verbose_name="Fin")),
                ("province", models.CharField(blank=True, max_length=80, verbose_name="Provincia")),
                ("canton", models.CharField(blank=True, max_length=80, verbose_name="Cantón")),
                ("parish", models.CharField(blank=True, max_length=80, verbose_name="Parroquia")),
                ("sector", models.CharField(blank=True, max_length=120, verbose_name="Sector / barrio")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="Dirección")),
                ("reference", models.CharField(blank=True, max_length=255, verbose_name="Referencia")),
                ("organizer_name", models.CharField(blank=True, max_length=180, verbose_name="Organizador / contacto")),
                ("organizer_phone", models.CharField(blank=True, max_length=32, verbose_name="Teléfono contacto")),
                ("expected_attendees", models.PositiveIntegerField(default=0, verbose_name="Asistentes esperados")),
                ("objective", models.TextField(blank=True, verbose_name="Objetivo")),
                ("logistics_notes", models.TextField(blank=True, verbose_name="Notas logísticas")),
                ("result_notes", models.TextField(blank=True, verbose_name="Resultado / seguimiento")),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agenda_events", to="campaigns.campaign", verbose_name="Campaña")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_agenda_events", to=settings.AUTH_USER_MODEL, verbose_name="Creado por")),
                ("responsible", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="responsible_agenda_events", to=settings.AUTH_USER_MODEL, verbose_name="Responsable")),
                ("source_request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agenda_events", to="political_agenda.politicalagendarequest", verbose_name="Solicitud origen")),
            ],
            options={
                "verbose_name": "Evento de agenda política",
                "verbose_name_plural": "Eventos de agenda política",
                "ordering": ["start_at", "title"],
                "permissions": (("schedule_politicalagendaevent", "Puede agendar eventos políticos"),),
            },
        ),
    ]
