# Generated by Codex on 2026-05-04

import apps.political_agenda.workflows
from django.db import migrations
import django_fsm


REQUEST_STATE_MAP = {
    "CANCELADA": 0,
    "PENDIENTE": 1,
    "EN_REVISION": 2,
    "APROBADA": 3,
    "RECHAZADA": 4,
}

EVENT_STATE_MAP = {
    "CANCELADO": 0,
    "BORRADOR": 1,
    "AGENDADO": 2,
    "REPROGRAMADO": 3,
    "REALIZADO": 4,
}


def copy_status_to_state(apps, schema_editor):
    AgendaRequest = apps.get_model("political_agenda", "PoliticalAgendaRequest")
    AgendaEvent = apps.get_model("political_agenda", "PoliticalAgendaEvent")
    for request in AgendaRequest.objects.all().only("pk", "status"):
        request.state = REQUEST_STATE_MAP.get(request.status, 1)
        request.save(update_fields=["state"])
    for event in AgendaEvent.objects.all().only("pk", "status"):
        event.state = EVENT_STATE_MAP.get(event.status, 1)
        event.save(update_fields=["state"])


class Migration(migrations.Migration):

    dependencies = [
        ("political_agenda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="politicalagendarequest",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(0, "Cancelada"), (1, "Pendiente"), (2, "En revisión"), (3, "Aprobada"), (4, "Rechazada")],
                default=apps.political_agenda.workflows.PoliticalAgendaRequestWorkflow.Choices["PENDING"],
                protected=True,
                verbose_name="Estado",
            ),
        ),
        migrations.AddField(
            model_name="politicalagendaevent",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(0, "Cancelado"), (1, "Borrador"), (2, "Agendado"), (3, "Reprogramado"), (4, "Realizado")],
                default=apps.political_agenda.workflows.PoliticalAgendaEventWorkflow.Choices["DRAFT"],
                protected=True,
                verbose_name="Estado",
            ),
        ),
        migrations.RunPython(copy_status_to_state, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="politicalagendarequest",
            name="status",
        ),
        migrations.RemoveField(
            model_name="politicalagendaevent",
            name="status",
        ),
        migrations.AlterModelOptions(
            name="politicalagendarequest",
            options={
                "ordering": ["-created_date"],
                "permissions": (
                    ("approve_politicalagendarequest", "Puede aprobar solicitudes de agenda política"),
                    ("reject_politicalagendarequest", "Puede rechazar solicitudes de agenda política"),
                ),
                "verbose_name": "Solicitud de agenda política",
                "verbose_name_plural": "Solicitudes de agenda política",
            },
        ),
    ]
