# Generated by Django 4.2.30 on 2026-05-05

from django.db import migrations, models
import django.db.models.deletion


def migrate_location_values(apps, schema_editor):
    Province = apps.get_model("locations", "Province")
    Canton = apps.get_model("locations", "Canton")
    Parish = apps.get_model("locations", "Parish")
    Sector = apps.get_model("locations", "Sector")
    Request = apps.get_model("political_agenda", "PoliticalAgendaRequest")
    Event = apps.get_model("political_agenda", "PoliticalAgendaEvent")

    province_by_name = {obj.name.lower(): obj.pk for obj in Province.objects.all()}
    canton_by_name = {obj.name.lower(): obj.pk for obj in Canton.objects.all()}
    parish_by_name = {obj.name.lower(): obj.pk for obj in Parish.objects.all()}
    sector_by_name = {obj.name.lower(): obj.pk for obj in Sector.objects.all()}

    for Model in (Request, Event):
        for obj in Model.objects.all():
            update_fields = []
            if getattr(obj, "province_text", ""):
                value = province_by_name.get(obj.province_text.lower())
                if value:
                    obj.province_id = value
                    update_fields.append("province")
            if getattr(obj, "canton_text", ""):
                value = canton_by_name.get(obj.canton_text.lower())
                if value:
                    obj.canton_id = value
                    update_fields.append("canton")
            if getattr(obj, "parish_text", ""):
                value = parish_by_name.get(obj.parish_text.lower())
                if value:
                    obj.parish_id = value
                    update_fields.append("parish")
            if getattr(obj, "sector_text", ""):
                value = sector_by_name.get(obj.sector_text.lower())
                if value:
                    obj.sector_id = value
                    update_fields.append("sector")
            if update_fields:
                obj.save(update_fields=update_fields)


def replace_location_fields(model_name, related_prefix):
    return [
        migrations.RenameField(model_name, "province", "province_text"),
        migrations.RenameField(model_name, "canton", "canton_text"),
        migrations.RenameField(model_name, "parish", "parish_text"),
        migrations.RenameField(model_name, "sector", "sector_text"),
        migrations.AddField(
            model_name=model_name.lower(),
            name="province",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name=related_prefix, to="locations.province", verbose_name="Provincia"),
        ),
        migrations.AddField(
            model_name=model_name.lower(),
            name="canton",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name=related_prefix, to="locations.canton", verbose_name="Cantón"),
        ),
        migrations.AddField(
            model_name=model_name.lower(),
            name="parish",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name=related_prefix, to="locations.parish", verbose_name="Parroquia"),
        ),
        migrations.AddField(
            model_name=model_name.lower(),
            name="sector",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name=related_prefix, to="locations.sector", verbose_name="Sector / barrio"),
        ),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_seed_ecuador"),
        ("political_agenda", "0002_use_workflow_states"),
    ]

    operations = [
        *replace_location_fields("PoliticalAgendaRequest", "agenda_requests"),
        *replace_location_fields("PoliticalAgendaEvent", "agenda_events"),
        migrations.RunPython(migrate_location_values, migrations.RunPython.noop),
        migrations.RemoveField("PoliticalAgendaRequest", "province_text"),
        migrations.RemoveField("PoliticalAgendaRequest", "canton_text"),
        migrations.RemoveField("PoliticalAgendaRequest", "parish_text"),
        migrations.RemoveField("PoliticalAgendaRequest", "sector_text"),
        migrations.RemoveField("PoliticalAgendaEvent", "province_text"),
        migrations.RemoveField("PoliticalAgendaEvent", "canton_text"),
        migrations.RemoveField("PoliticalAgendaEvent", "parish_text"),
        migrations.RemoveField("PoliticalAgendaEvent", "sector_text"),
    ]
