# Generated by Django 4.2.30 on 2026-05-08 20:15

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_agenda', '0007_politicalagendaevent_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaeventtype',
            name='color',
            field=core.fields.ColorField(default='#3e97ff', help_text='Hex #RRGGBB usado en el calendario y badges.', max_length=9, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='politicalagendaevent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Activado: visible para todo el equipo del partido.<details class="cm-help-disclosure"><summary></summary><p>Si lo desactivas, solo los usuarios con el permiso «Puede ver eventos privados» podrán verlo en el listado y el calendario.</p></details>', verbose_name='Visible al público'),
        ),
    ]
