# Generated by Django 4.2.30 on 2026-05-08 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_agenda', '0008_alter_agendaeventtype_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaeventtype',
            name='icon',
            field=models.CharField(default='calendar-tick', help_text='Nombre del ícono Keenicons (sin el prefijo ki-).', max_length=60, validators=[django.core.validators.RegexValidator(code='invalid_icon_name', message="Usa el nombre del ícono Keenicons en minúsculas, sin el prefijo 'ki-' (ej. 'calendar-tick').", regex='^[a-z0-9][a-z0-9-]*$')], verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='politicalagendaevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90, message='La latitud debe estar entre -90 y 90.'), django.core.validators.MaxValueValidator(90, message='La latitud debe estar entre -90 y 90.')], verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='politicalagendaevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180, message='La longitud debe estar entre -180 y 180.'), django.core.validators.MaxValueValidator(180, message='La longitud debe estar entre -180 y 180.')], verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='politicalagendarequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90, message='La latitud debe estar entre -90 y 90.'), django.core.validators.MaxValueValidator(90, message='La latitud debe estar entre -90 y 90.')], verbose_name='Latitud tentativa'),
        ),
        migrations.AlterField(
            model_name='politicalagendarequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180, message='La longitud debe estar entre -180 y 180.'), django.core.validators.MaxValueValidator(180, message='La longitud debe estar entre -180 y 180.')], verbose_name='Longitud tentativa'),
        ),
    ]
