# Generated by Django 4.2.30 on 2026-06-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_agenda', '0009_alter_agendaeventtype_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalagendaevent',
            name='private_reference',
            field=models.CharField(blank=True, help_text='Texto opcional visible para todo el equipo cuando el evento es privado (ej. «Fuera de la ciudad»).', max_length=180, verbose_name='Referencia del evento privado'),
        ),
        migrations.AlterField(
            model_name='politicalagendaevent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Activado: visible para todo el equipo del partido.<details class="cm-help-disclosure"><summary></summary><p>Si lo desactivas, el resto del equipo solo verá el horario como «Ocupado» (con la referencia opcional); el detalle queda reservado a los usuarios con el permiso «Puede ver eventos privados».</p></details>', verbose_name='Visible al público'),
        ),
    ]
