# Generated by Django 4.2.30 on 2026-05-07 17:02

import apps.territorial_ads.transitions
import apps.territorial_ads.workflows
import core.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_surveys', '0001_initial'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingCostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('requires_amount', models.BooleanField(default=False, help_text='Si está activo, se exige capturar el monto acordado.', verbose_name='Requiere monto')),
            ],
            options={
                'verbose_name': 'Tipo de costo de publicidad',
                'verbose_name_plural': 'Tipos de costo de publicidad',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('code', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Código')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad')),
                ('width_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ancho (m)')),
                ('height_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Alto (m)')),
                ('owner_name', models.CharField(max_length=180, verbose_name='Propietario / contacto')),
                ('owner_phone', models.CharField(max_length=32, verbose_name='Teléfono contacto')),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Sólo si el tipo de costo lo requiere.', max_digits=10, null=True, verbose_name='Monto acordado')),
                ('offered_notes', models.TextField(blank=True, verbose_name='Condiciones ofrecidas')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Referencia')),
                ('offered_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud referencial')),
                ('offered_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud referencial')),
                ('offered_photo', core.fields.CompressedImageField(blank=True, null=True, upload_to='territorial_ads/offered/', verbose_name='Foto del lugar ofrecido')),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'Rechazada'), (1, 'Ofrecida'), (2, 'Aprobada'), (3, 'Pendiente instalación'), (4, 'Instalada'), (5, 'Dañada'), (6, 'Retirada')], default=apps.territorial_ads.workflows.PhysicalAdWorkflow.Choices['OFRECIDA'], protected=True, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('installation_instructions', models.TextField(blank=True, help_text='Indica qué se requiere para instalar (escalera, andamio, permisos, etc.).', verbose_name='Instrucciones para instalación')),
                ('installer_team', models.CharField(blank=True, max_length=180, verbose_name='Equipo instalador')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('installation_photo', core.fields.CompressedImageField(blank=True, null=True, upload_to='territorial_ads/installations/', verbose_name='Foto de evidencia')),
                ('installed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud GPS instalación')),
                ('installed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud GPS instalación')),
                ('installed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora instalación')),
                ('installation_notes', models.TextField(blank=True, verbose_name='Notas de instalación')),
                ('damage_notes', models.TextField(blank=True, verbose_name='Notas de daño')),
                ('damage_photo', core.fields.CompressedImageField(blank=True, null=True, upload_to='territorial_ads/damages/', verbose_name='Foto de daño')),
                ('damage_reported_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha reporte daño')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de rechazo')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de rechazo')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha retiro')),
                ('advertisement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_advertisements', to='field_surveys.advertisingtype', verbose_name='Tipo de publicidad')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_physical_ad_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('assigned_installer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Instalador asignado')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_advertisements', to='campaigns.campaign', verbose_name='Campaña')),
                ('cost_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_advertisements', to='territorial_ads.advertisingcosttype', verbose_name='Tipo de costo')),
                ('damage_reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_reported_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Daño reportado por')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Usuario instalador')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Rechazado por')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidad',
                'ordering': ['-created_date'],
                'permissions': (('approve_physicaladvertisement', 'Puede aprobar publicidad'), ('reject_physicaladvertisement', 'Puede rechazar publicidad'), ('assign_physicaladvertisement', 'Puede asignar instalación de publicidad'), ('install_physicaladvertisement', 'Puede registrar instalación de publicidad'), ('report_damage_physicaladvertisement', 'Puede reportar daño de publicidad'), ('retire_physicaladvertisement', 'Puede retirar publicidad')),
            },
            bases=(models.Model, apps.territorial_ads.transitions.PhysicalAdTransitions),
        ),
    ]
