# Generated by Django 4.2.30 on 2026-05-04 19:08

import apps.territorial_ads.workflows
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_alter_campaign_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('advertisement_type', models.CharField(choices=[('lona', 'Lona'), ('valla', 'Valla'), ('afiche', 'Afiche'), ('otro', 'Otro')], default='lona', max_length=24, verbose_name='Tipo de publicidad')),
                ('code', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Código')),
                ('title', models.CharField(max_length=180, verbose_name='Identificación')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad')),
                ('width_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ancho (m)')),
                ('height_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Alto (m)')),
                ('owner_name', models.CharField(max_length=180, verbose_name='Dueño / contacto')),
                ('owner_phone', models.CharField(max_length=32, verbose_name='Teléfono contacto')),
                ('owner_identification', models.CharField(blank=True, max_length=20, verbose_name='Identificación contacto')),
                ('offered_notes', models.TextField(blank=True, verbose_name='Condiciones ofrecidas')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='Provincia')),
                ('canton', models.CharField(blank=True, max_length=80, verbose_name='Cantón')),
                ('parish', models.CharField(blank=True, max_length=80, verbose_name='Parroquia')),
                ('sector', models.CharField(blank=True, max_length=120, verbose_name='Sector / barrio')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Referencia')),
                ('offered_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud referencial')),
                ('offered_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud referencial')),
                ('state', django_fsm.FSMIntegerField(choices=[(1, 'Ofrecida'), (2, 'Aprobada'), (3, 'Pendiente instalación'), (4, 'Instalada'), (5, 'Dañada'), (6, 'Retirada')], default=apps.territorial_ads.workflows.PhysicalAdWorkflow.Choices['OFRECIDA'], protected=True, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('installer_team', models.CharField(blank=True, max_length=180, verbose_name='Equipo instalador')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('installation_photo', models.ImageField(blank=True, null=True, upload_to='territorial_ads/installations/', verbose_name='Foto de evidencia')),
                ('installed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud GPS instalación')),
                ('installed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud GPS instalación')),
                ('installed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora instalación')),
                ('installation_notes', models.TextField(blank=True, verbose_name='Notas de instalación')),
                ('damage_notes', models.TextField(blank=True, verbose_name='Notas de daño')),
                ('damage_photo', models.ImageField(blank=True, null=True, upload_to='territorial_ads/damages/', verbose_name='Foto de daño')),
                ('damage_reported_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha reporte daño')),
                ('retirement_notes', models.TextField(blank=True, verbose_name='Notas de retiro')),
                ('retirement_photo', models.ImageField(blank=True, null=True, upload_to='territorial_ads/retirements/', verbose_name='Foto de retiro')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha retiro')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_physical_ad_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('assigned_installer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Instalador asignado')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_advertisements', to='campaigns.campaign', verbose_name='Campaña')),
                ('damage_reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_reported_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Daño reportado por')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Usuario instalador')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_physical_ads', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por')),
            ],
            options={
                'verbose_name': 'Publicidad física',
                'verbose_name_plural': 'Publicidad física',
                'ordering': ['-created_date'],
                'permissions': (('approve_physicaladvertisement', 'Puede aprobar publicidad física'), ('assign_physicaladvertisement', 'Puede asignar instalación de publicidad física'), ('install_physicaladvertisement', 'Puede registrar instalación de publicidad física'), ('report_damage_physicaladvertisement', 'Puede reportar daño de publicidad física'), ('retire_physicaladvertisement', 'Puede retirar publicidad física')),
            },
        ),
    ]
