# Generated by Django 4.2.30 on 2026-05-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territorial_ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicaladvertisement',
            name='owner_identification',
        ),
    ]
