# Generated by Django 4.2.30 on 2026-05-05

from django.db import migrations, models
import django.db.models.deletion


def migrate_location_values(apps, schema_editor):
    Province = apps.get_model("locations", "Province")
    Canton = apps.get_model("locations", "Canton")
    Parish = apps.get_model("locations", "Parish")
    Sector = apps.get_model("locations", "Sector")
    PhysicalAdvertisement = apps.get_model("territorial_ads", "PhysicalAdvertisement")

    province_by_name = {obj.name.lower(): obj.pk for obj in Province.objects.all()}
    canton_by_name = {obj.name.lower(): obj.pk for obj in Canton.objects.all()}
    parish_by_name = {obj.name.lower(): obj.pk for obj in Parish.objects.all()}
    sector_by_name = {obj.name.lower(): obj.pk for obj in Sector.objects.all()}

    for obj in PhysicalAdvertisement.objects.all():
        update_fields = []
        if getattr(obj, "province_text", ""):
            value = province_by_name.get(obj.province_text.lower())
            if value:
                obj.province_id = value
                update_fields.append("province")
        if getattr(obj, "canton_text", ""):
            value = canton_by_name.get(obj.canton_text.lower())
            if value:
                obj.canton_id = value
                update_fields.append("canton")
        if getattr(obj, "parish_text", ""):
            value = parish_by_name.get(obj.parish_text.lower())
            if value:
                obj.parish_id = value
                update_fields.append("parish")
        if getattr(obj, "sector_text", ""):
            value = sector_by_name.get(obj.sector_text.lower())
            if value:
                obj.sector_id = value
                update_fields.append("sector")
        if update_fields:
            obj.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_seed_ecuador"),
        ("territorial_ads", "0002_remove_physicaladvertisement_owner_identification"),
    ]

    operations = [
        migrations.RenameField("PhysicalAdvertisement", "province", "province_text"),
        migrations.RenameField("PhysicalAdvertisement", "canton", "canton_text"),
        migrations.RenameField("PhysicalAdvertisement", "parish", "parish_text"),
        migrations.RenameField("PhysicalAdvertisement", "sector", "sector_text"),
        migrations.AddField(
            model_name="physicaladvertisement",
            name="province",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="physical_advertisements", to="locations.province", verbose_name="Provincia"),
        ),
        migrations.AddField(
            model_name="physicaladvertisement",
            name="canton",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="physical_advertisements", to="locations.canton", verbose_name="Cantón"),
        ),
        migrations.AddField(
            model_name="physicaladvertisement",
            name="parish",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="physical_advertisements", to="locations.parish", verbose_name="Parroquia"),
        ),
        migrations.AddField(
            model_name="physicaladvertisement",
            name="sector",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="physical_advertisements", to="locations.sector", verbose_name="Sector / barrio"),
        ),
        migrations.RunPython(migrate_location_values, migrations.RunPython.noop),
        migrations.RemoveField("PhysicalAdvertisement", "province_text"),
        migrations.RemoveField("PhysicalAdvertisement", "canton_text"),
        migrations.RemoveField("PhysicalAdvertisement", "parish_text"),
        migrations.RemoveField("PhysicalAdvertisement", "sector_text"),
    ]
