# Generated by Django 4.2.30 on 2026-06-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorial_ads', '0003_alter_advertisingrefusal_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaladvertisement',
            name='installer_team',
            field=models.CharField(blank=True, max_length=180, verbose_name='Instalador externo'),
        ),
    ]
