# Generated by Django 4.2.30 on 2026-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorial_ads', '0004_remove_physicaladvertisement_location_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaladvertisement',
            name='installation_instructions',
            field=models.TextField(blank=True, help_text='Indica qué se requiere para instalar (escalera, andamio, permisos, etc.).', verbose_name='Instrucciones para instalación'),
        ),
    ]
