# Generated by Django 4.2.30 on 2026-06-12 17:43

import core.fields
from django.db import migrations, models
import django.db.models.deletion


def copy_legacy_fields_to_related(apps, schema_editor):
    """Move the old single type/quantity/photo columns into the new models."""
    PhysicalAdvertisement = apps.get_model("territorial_ads", "PhysicalAdvertisement")
    PhysicalAdvertisementItem = apps.get_model(
        "territorial_ads", "PhysicalAdvertisementItem"
    )
    InstallationPhoto = apps.get_model("territorial_ads", "InstallationPhoto")
    for ad in PhysicalAdvertisement.objects.all().iterator():
        if ad.advertisement_type_id:
            PhysicalAdvertisementItem.objects.create(
                advertisement=ad,
                advertisement_type_id=ad.advertisement_type_id,
                quantity=ad.quantity or 1,
                installation_instructions=ad.installation_instructions or "",
            )
        if ad.installation_photo:
            InstallationPhoto.objects.create(
                advertisement=ad,
                photo=ad.installation_photo.name,
            )


def restore_legacy_fields(apps, schema_editor):
    PhysicalAdvertisement = apps.get_model("territorial_ads", "PhysicalAdvertisement")
    for ad in PhysicalAdvertisement.objects.all().iterator():
        item = ad.items.order_by("id").first()
        if item is not None:
            ad.advertisement_type_id = item.advertisement_type_id
            ad.quantity = item.quantity
            ad.installation_instructions = item.installation_instructions
        photo = ad.installation_photos.order_by("id").first()
        if photo is not None:
            ad.installation_photo = photo.photo.name
        ad.save()


class Migration(migrations.Migration):

    dependencies = [
        ('field_surveys', '0007_alter_advertisingtype_icon_and_more'),
        ('territorial_ads', '0004_alter_physicaladvertisement_installer_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalAdvertisementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad')),
                ('installation_instructions', models.TextField(blank=True, help_text='Indica qué se requiere para instalar este tipo (escalera, andamio, permisos, etc.).', verbose_name='Indicaciones para instalación')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='territorial_ads.physicaladvertisement', verbose_name='Publicidad')),
                ('advertisement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_ad_items', to='field_surveys.advertisingtype', verbose_name='Tipo de publicidad')),
            ],
            options={
                'verbose_name': 'Tipo de publicidad del lugar',
                'verbose_name_plural': 'Tipos de publicidad del lugar',
                'ordering': ['advertisement_type__order', 'advertisement_type__name'],
            },
        ),
        migrations.CreateModel(
            name='InstallationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('photo', core.fields.CompressedImageField(upload_to='territorial_ads/installations/', verbose_name='Foto de evidencia')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_photos', to='territorial_ads.physicaladvertisement', verbose_name='Publicidad')),
            ],
            options={
                'verbose_name': 'Foto de instalación',
                'verbose_name_plural': 'Fotos de instalación',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='physicaladvertisementitem',
            constraint=models.UniqueConstraint(fields=('advertisement', 'advertisement_type'), name='unique_type_per_advertisement'),
        ),
        migrations.RunPython(copy_legacy_fields_to_related, restore_legacy_fields),
        migrations.RemoveField(
            model_name='physicaladvertisement',
            name='advertisement_type',
        ),
        migrations.RemoveField(
            model_name='physicaladvertisement',
            name='installation_instructions',
        ),
        migrations.RemoveField(
            model_name='physicaladvertisement',
            name='installation_photo',
        ),
        migrations.RemoveField(
            model_name='physicaladvertisement',
            name='quantity',
        ),
    ]
