# Generated by Django 4.2.30 on 2026-06-12 20:55

import apps.territorial_ads.transitions
import apps.territorial_ads.workflows
import core.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('field_surveys', '0008_competitor_acronym'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('territorial_ads', '0005_remove_physicaladvertisement_advertisement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingTypeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('advertisement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='field_surveys.advertisingtype', verbose_name='Tipo de publicidad')),
            ],
            options={
                'verbose_name': 'Tamaño de publicidad',
                'verbose_name_plural': 'Tamaños de publicidad',
                'ordering': ['advertisement_type__order', 'advertisement_type__name', 'order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='physicaladvertisement',
            options={'ordering': ['-created_date'], 'permissions': (('approve_physicaladvertisement', 'Puede aprobar publicidad'), ('reject_physicaladvertisement', 'Puede rechazar publicidad'), ('assign_physicaladvertisement', 'Puede asignar instalación de publicidad'), ('install_physicaladvertisement', 'Puede registrar instalación de publicidad'), ('report_damage_physicaladvertisement', 'Puede reportar daño de publicidad'), ('retire_physicaladvertisement', 'Puede retirar publicidad')), 'verbose_name': 'Solicitud de publicidad', 'verbose_name_plural': 'Solicitudes de publicidad'},
        ),
        migrations.CreateModel(
            name='PhysicalAdvertisementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('unit_number', models.PositiveSmallIntegerField(default=1, verbose_name='Unidad')),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'Retirada'), (1, 'Pendiente instalación'), (2, 'Instalada'), (3, 'Dañada')], default=apps.territorial_ads.workflows.PhysicalAdUnitWorkflow.Choices['PENDIENTE'], protected=True, verbose_name='Estado')),
                ('photo', core.fields.CompressedImageField(blank=True, null=True, upload_to='territorial_ads/installations/', verbose_name='Foto de evidencia')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90, message='La latitud debe estar entre -90 y 90.'), django.core.validators.MaxValueValidator(90, message='La latitud debe estar entre -90 y 90.')], verbose_name='Latitud GPS')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180, message='La longitud debe estar entre -180 y 180.'), django.core.validators.MaxValueValidator(180, message='La longitud debe estar entre -180 y 180.')], verbose_name='Longitud GPS')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de instalación')),
                ('installed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora instalación')),
                ('damage_notes', models.TextField(blank=True, verbose_name='Notas de daño')),
                ('damage_photo', core.fields.CompressedImageField(blank=True, null=True, upload_to='territorial_ads/damages/', verbose_name='Foto de daño')),
                ('damage_reported_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha reporte daño')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha retiro')),
                ('damage_reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_reported_ad_units', to=settings.AUTH_USER_MODEL, verbose_name='Daño reportado por')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_ad_units', to=settings.AUTH_USER_MODEL, verbose_name='Instalado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='territorial_ads.physicaladvertisementitem', verbose_name='Ítem solicitado')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_ad_units', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='territorial_ads.advertisingtypesize', verbose_name='Tamaño')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
                'ordering': ['item__advertisement_type__order', 'item_id', 'unit_number'],
            },
            bases=(models.Model, apps.territorial_ads.transitions.PhysicalAdUnitTransitions),
        ),
        migrations.AddConstraint(
            model_name='physicaladvertisementunit',
            constraint=models.UniqueConstraint(fields=('item', 'unit_number'), name='unique_unit_number_per_item'),
        ),
        migrations.AddConstraint(
            model_name='advertisingtypesize',
            constraint=models.UniqueConstraint(fields=('advertisement_type', 'name'), name='unique_size_name_per_type'),
        ),
    ]
