# Generated by Django 4.2.30 on 2026-05-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorial_ads', '0006_remove_physicaladvertisement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaladvertisement',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Sólo si el tipo de costo es 'Pagada'.", max_digits=10, null=True, verbose_name='Monto acordado'),
        ),
        migrations.AddField(
            model_name='physicaladvertisement',
            name='cost_type',
            field=models.CharField(choices=[('gratuita', 'Gratuita'), ('pagada', 'Pagada'), ('donada', 'Donada'), ('canje', 'Canje / permuta')], default='gratuita', max_length=16, verbose_name='Tipo de costo'),
        ),
    ]
