# Generated by Django 4.2.30 on 2026-06-15 16:12

import apps.territorial_ads.workflows
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('territorial_ads', '0007_materialize_units_for_existing_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaladvertisementunit',
            name='code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='physicaladvertisement',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Rechazada'), (1, 'Ofrecida'), (2, 'Aprobada'), (3, 'Pendiente instalación'), (4, 'Instalada')], default=apps.territorial_ads.workflows.PhysicalAdWorkflow.Choices['OFRECIDA'], protected=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='physicaladvertisementunit',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Retirada'), (1, 'Pendiente instalación'), (2, 'Instalada'), (3, 'Dañada'), (4, 'No instalada')], default=apps.territorial_ads.workflows.PhysicalAdUnitWorkflow.Choices['PENDIENTE'], protected=True, verbose_name='Estado'),
        ),
    ]
