# Generated by Django 4.2.30 on 2026-05-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_state'),
        ('territorial_ads', '0008_advertisingcosttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaladvertisement',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_advertisements', to='campaigns.campaign', verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='physicaladvertisement',
            name='owner_name',
            field=models.CharField(max_length=180, verbose_name='Propietario / contacto'),
        ),
    ]
