# Generated by Django 4.2.30 on 2026-06-15 19:30

import apps.territorial_ads.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('territorial_ads', '0009_codes_and_state_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaladvertisement',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Rechazada'), (1, 'Ofrecida'), (2, 'Aprobada'), (3, 'Pendiente instalación'), (4, 'Instalada'), (5, 'Retirada')], default=apps.territorial_ads.workflows.PhysicalAdWorkflow.Choices['OFRECIDA'], protected=True, verbose_name='Estado'),
        ),
    ]
