# Generated by Django 4.2.30 on 2026-05-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorial_ads', '0009_alter_physicaladvertisement_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaladvertisement',
            name='offered_photo',
            field=models.ImageField(blank=True, null=True, upload_to='territorial_ads/offered/', verbose_name='Foto del lugar ofrecido'),
        ),
    ]
