# Generated by Django 4.2.30 on 2026-05-06 18:00

import apps.territorial_ads.workflows
import core.fields
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('territorial_ads', '0011_physicaladvertisement_rejection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaladvertisement',
            name='damage_photo',
            field=core.fields.CompressedImageField(blank=True, null=True, upload_to='territorial_ads/damages/', verbose_name='Foto de daño'),
        ),
        migrations.AlterField(
            model_name='physicaladvertisement',
            name='installation_photo',
            field=core.fields.CompressedImageField(blank=True, null=True, upload_to='territorial_ads/installations/', verbose_name='Foto de evidencia'),
        ),
        migrations.AlterField(
            model_name='physicaladvertisement',
            name='offered_photo',
            field=core.fields.CompressedImageField(blank=True, null=True, upload_to='territorial_ads/offered/', verbose_name='Foto del lugar ofrecido'),
        ),
        migrations.AlterField(
            model_name='physicaladvertisement',
            name='retirement_photo',
            field=core.fields.CompressedImageField(blank=True, null=True, upload_to='territorial_ads/retirements/', verbose_name='Foto de retiro'),
        ),
        migrations.AlterField(
            model_name='physicaladvertisement',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Rechazada'), (1, 'Ofrecida'), (2, 'Aprobada'), (3, 'Pendiente instalación'), (4, 'Instalada'), (5, 'Dañada'), (6, 'Retirada')], default=apps.territorial_ads.workflows.PhysicalAdWorkflow.Choices['OFRECIDA'], protected=True, verbose_name='Estado'),
        ),
    ]
