# Generated by Django 4.2.30 on 2026-06-15 20:13

from django.db import migrations, models


def copy_instructions_to_units(apps, schema_editor):
    """Carry per-item instructions over to each of the item's units."""
    Unit = apps.get_model("territorial_ads", "PhysicalAdvertisementUnit")
    for unit in Unit.objects.select_related("item").all():
        instructions = unit.item.installation_instructions
        if instructions:
            unit.installation_instructions = instructions
            unit.save(update_fields=["installation_instructions"])


class Migration(migrations.Migration):

    dependencies = [
        ('territorial_ads', '0011_rederive_retired_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaladvertisementunit',
            name='installation_instructions',
            field=models.TextField(blank=True, help_text='Indica qué se requiere para instalar esta unidad (escalera, andamio, permisos, etc.).', verbose_name='Indicaciones para instalación'),
        ),
        migrations.RunPython(
            copy_instructions_to_units, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='physicaladvertisementitem',
            name='installation_instructions',
        ),
    ]
