# Generated by Django 4.2.30 on 2026-06-15 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_assignment_to_units(apps, schema_editor):
    """Carry the request-level installer assignment onto each of its units."""
    Unit = apps.get_model("territorial_ads", "PhysicalAdvertisementUnit")
    for unit in Unit.objects.select_related("item__advertisement").all():
        ad = unit.item.advertisement
        unit.assigned_installer_id = ad.assigned_installer_id
        unit.installer_team = ad.installer_team or ""
        unit.assigned_by_id = ad.assigned_by_id
        unit.assigned_at = ad.assigned_at
        unit.save(
            update_fields=[
                "assigned_installer",
                "installer_team",
                "assigned_by",
                "assigned_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('territorial_ads', '0012_remove_physicaladvertisementitem_installation_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaladvertisementunit',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AddField(
            model_name='physicaladvertisementunit',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_ad_unit_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AddField(
            model_name='physicaladvertisementunit',
            name='assigned_installer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_ad_units', to=settings.AUTH_USER_MODEL, verbose_name='Instalador asignado'),
        ),
        migrations.AddField(
            model_name='physicaladvertisementunit',
            name='installer_team',
            field=models.CharField(blank=True, max_length=180, verbose_name='Instalador externo'),
        ),
        migrations.RunPython(copy_assignment_to_units, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='physicaladvertisement',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='physicaladvertisement',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='physicaladvertisement',
            name='assigned_installer',
        ),
        migrations.RemoveField(
            model_name='physicaladvertisement',
            name='installer_team',
        ),
    ]
