# Generated by Django 4.2.30 on 2026-07-02 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralCandidateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('list_code', models.CharField(max_length=32, verbose_name='Lista')),
                ('candidate_name', models.CharField(max_length=180, verbose_name='Candidato')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Candidatura electoral',
                'verbose_name_plural': 'Candidaturas electorales',
                'ordering': ['district__dignity__order', 'district__order', 'order', 'list_code'],
            },
        ),
        migrations.CreateModel(
            name='ElectoralDignity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Dignidad')),
                ('scope', models.CharField(choices=[('province', 'Provincia'), ('canton', 'Cantón'), ('district', 'Circunscripción'), ('parish', 'Parroquia')], max_length=20, verbose_name='Ámbito')),
                ('parish_kind_rule', models.CharField(choices=[('all', 'Todas'), ('urban', 'Solo urbanas'), ('rural', 'Solo rurales')], default='all', max_length=20, verbose_name='Tipo de parroquia')),
                ('seats', models.PositiveSmallIntegerField(default=1, verbose_name='Escaños')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Dignidad electoral',
                'verbose_name_plural': 'Dignidades electorales',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElectoralDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=180, verbose_name='Circunscripción')),
                ('kind', models.CharField(choices=[('province', 'Provincia'), ('canton', 'Cantón'), ('urban', 'Urbana'), ('rural', 'Rural'), ('parish', 'Parroquial')], max_length=20, verbose_name='Tipo')),
                ('seats', models.PositiveSmallIntegerField(default=1, verbose_name='Escaños')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vote_districts', to='locations.canton', verbose_name='Cantón')),
                ('dignity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='votes.electoraldignity', verbose_name='Dignidad')),
                ('parishes', models.ManyToManyField(blank=True, related_name='vote_districts', to='locations.parish', verbose_name='Parroquias')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vote_districts', to='locations.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Circunscripción electoral',
                'verbose_name_plural': 'Circunscripciones electorales',
                'ordering': ['dignity__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElectoralTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('number', models.CharField(max_length=24, verbose_name='Mesa')),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('X', 'Mixta')], default='X', max_length=1, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Mesa electoral',
                'verbose_name_plural': 'Mesas electorales',
                'ordering': ['venue__parish__name', 'venue__name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ElectoralVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=180, verbose_name='Recinto electoral')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90, message='La latitud debe estar entre -90 y 90.'), django.core.validators.MaxValueValidator(90, message='La latitud debe estar entre -90 y 90.')], verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180, message='La longitud debe estar entre -180 y 180.'), django.core.validators.MaxValueValidator(180, message='La longitud debe estar entre -180 y 180.')], verbose_name='Longitud')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_venues', to='locations.parish', verbose_name='Parroquia')),
            ],
            options={
                'verbose_name': 'Recinto electoral',
                'verbose_name_plural': 'Recintos electorales',
                'ordering': ['parish__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElectoralTableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('notes', models.CharField(blank=True, max_length=240, verbose_name='Observaciones')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='votes.electoraltable', verbose_name='Mesa')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_table_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Veedor')),
            ],
            options={
                'verbose_name': 'Asignación de mesa',
                'verbose_name_plural': 'Asignaciones de mesas',
                'ordering': ['table__venue__parish__name', 'table__venue__name', 'table__number'],
            },
        ),
        migrations.AddField(
            model_name='electoraltable',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='votes.electoralvenue', verbose_name='Recinto'),
        ),
        migrations.CreateModel(
            name='ElectoralResultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Ingresada'), ('observed', 'Observada'), ('validated', 'Validada'), ('rejected', 'Rechazada')], default='submitted', max_length=20, verbose_name='Estado')),
                ('voters_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sufragantes')),
                ('validation_notes', models.TextField(blank=True, verbose_name='Observaciones de validación')),
                ('dignity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_reports', to='votes.electoraldignity', verbose_name='Dignidad')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_reports', to='votes.electoraldistrict', verbose_name='Circunscripción')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_result_reports', to='locations.parish', verbose_name='Parroquia')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_reports', to='votes.electoraltable', verbose_name='Mesa')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_reports', to='votes.electoralvenue', verbose_name='Recinto electoral')),
                ('watcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_result_reports', to=settings.AUTH_USER_MODEL, verbose_name='Veedor')),
            ],
            options={
                'verbose_name': 'Acta de resultado electoral',
                'verbose_name_plural': 'Actas de resultados electorales',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ElectoralResultLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('line_type', models.CharField(choices=[('candidate', 'Candidato'), ('blank', 'Blancos'), ('null', 'Nulos')], default='candidate', max_length=20, verbose_name='Tipo')),
                ('list_code', models.CharField(max_length=32, verbose_name='Lista')),
                ('candidate_name', models.CharField(blank=True, max_length=180, verbose_name='Candidato')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Votos')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('candidate_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_lines', to='votes.electoralcandidateoption', verbose_name='Candidatura')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='votes.electoralresultreport', verbose_name='Acta')),
            ],
            options={
                'verbose_name': 'Línea de resultado electoral',
                'verbose_name_plural': 'Líneas de resultados electorales',
                'ordering': ['report', 'order', 'list_code'],
            },
        ),
        migrations.AddField(
            model_name='electoralcandidateoption',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_options', to='votes.electoraldistrict', verbose_name='Circunscripción'),
        ),
        migrations.AddConstraint(
            model_name='electoralvenue',
            constraint=models.UniqueConstraint(fields=('parish', 'name'), name='votes_unique_electoral_venue_per_parish'),
        ),
        migrations.AddConstraint(
            model_name='electoraltableassignment',
            constraint=models.UniqueConstraint(fields=('table', 'watcher'), name='votes_unique_table_watcher_assignment'),
        ),
        migrations.AddConstraint(
            model_name='electoraltable',
            constraint=models.UniqueConstraint(fields=('venue', 'number', 'gender'), name='votes_unique_electoral_table'),
        ),
        migrations.AddConstraint(
            model_name='electoralresultreport',
            constraint=models.UniqueConstraint(fields=('table', 'dignity', 'district'), name='votes_unique_electoral_result_report'),
        ),
        migrations.AddConstraint(
            model_name='electoraldistrict',
            constraint=models.UniqueConstraint(fields=('dignity', 'name'), name='votes_unique_electoral_district_name'),
        ),
        migrations.AddConstraint(
            model_name='electoralcandidateoption',
            constraint=models.UniqueConstraint(fields=('district', 'list_code', 'candidate_name'), name='votes_unique_electoral_candidate_option'),
        ),
    ]
