# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="electoralresultreport",
            name="evidence_file",
            field=models.FileField(
                blank=True,
                upload_to="votes/reports/evidence/%Y/%m/",
                verbose_name="Evidencia del acta",
            ),
        ),
        migrations.AddField(
            model_name="electoraltable",
            name="registered_voters",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Electores registrados",
            ),
        ),
    ]
