# Generated by Django 4.2.30 on 2026-07-02 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("title", models.CharField(max_length=180, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicada"),
                            ("closed", "Cerrada"),
                            ("archived", "Archivada"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Inicio"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Anónima"),
                ),
                (
                    "requires_login",
                    models.BooleanField(
                        default=True, verbose_name="Requiere inicio de sesión"
                    ),
                ),
                (
                    "allow_multiple_responses",
                    models.BooleanField(
                        default=False, verbose_name="Permite varias respuestas"
                    ),
                ),
                (
                    "thank_you_message",
                    models.CharField(
                        blank=True,
                        default="Gracias. Tu respuesta fue registrada.",
                        max_length=240,
                        verbose_name="Mensaje de confirmación",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_surveys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encuesta",
                "verbose_name_plural": "Encuestas",
                "ordering": ["-created_date"],
                "permissions": (
                    ("publish_survey", "Puede publicar/cerrar encuestas"),
                    ("view_survey_results", "Puede ver resultados de encuestas"),
                    ("export_survey_results", "Puede exportar resultados de encuestas"),
                ),
            },
        ),
        migrations.CreateModel(
            name="SurveySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("title", models.CharField(max_length=180, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="surveys.survey",
                        verbose_name="Encuesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección de encuesta",
                "verbose_name_plural": "Secciones de encuesta",
                "ordering": ["survey", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "respondent_name",
                    models.CharField(blank=True, max_length=180, verbose_name="Nombre"),
                ),
                (
                    "respondent_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviada"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="Navegador")),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="surveys.survey",
                        verbose_name="Encuesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de encuesta",
                "verbose_name_plural": "Respuestas de encuesta",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("text", models.CharField(max_length=300, verbose_name="Pregunta")),
                (
                    "help_text",
                    models.CharField(blank=True, max_length=240, verbose_name="Ayuda"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Texto corto"),
                            ("long_text", "Texto largo"),
                            ("number", "Número"),
                            ("date", "Fecha"),
                            ("time", "Hora"),
                            ("yes_no", "Sí/No"),
                            ("single_choice", "Selección única"),
                            ("multiple_choice", "Selección múltiple"),
                            ("scale_5", "Escala 1-5"),
                            ("scale_10", "Escala 1-10"),
                            ("email", "Correo"),
                            ("phone", "Teléfono"),
                            ("file", "Archivo"),
                            ("image", "Imagen"),
                            ("location", "Ubicación GPS"),
                        ],
                        default="short_text",
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Obligatoria"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="surveys.surveysection",
                        verbose_name="Sección",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="surveys.survey",
                        verbose_name="Encuesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta de encuesta",
                "verbose_name_plural": "Preguntas de encuesta",
                "ordering": ["survey", "section__order", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SurveyOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("label", models.CharField(max_length=180, verbose_name="Opción")),
                (
                    "value",
                    models.CharField(blank=True, max_length=180, verbose_name="Valor"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="surveys.surveyquestion",
                        verbose_name="Pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción de encuesta",
                "verbose_name_plural": "Opciones de encuesta",
                "ordering": ["question", "order", "label"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("value_text", models.TextField(blank=True, verbose_name="Respuesta")),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "value_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "value_time",
                    models.TimeField(blank=True, null=True, verbose_name="Hora"),
                ),
                (
                    "value_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="surveys/answers/files/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="surveys.surveyquestion",
                        verbose_name="Pregunta",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="surveys.surveyresponse",
                        verbose_name="Respuesta",
                    ),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(
                        blank=True,
                        related_name="answers",
                        to="surveys.surveyoption",
                        verbose_name="Opciones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta a pregunta",
                "verbose_name_plural": "Respuestas a preguntas",
                "ordering": ["response", "question__order"],
            },
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.UniqueConstraint(
                fields=("response", "question"),
                name="surveys_unique_answer_per_question",
            ),
        ),
    ]
