# Generated by Django 4.2.30 on 2026-07-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="visibility_operator",
            field=models.CharField(
                choices=[
                    ("always", "Siempre visible"),
                    ("equals", "Mostrar si es igual a"),
                    ("not_equals", "Mostrar si es distinto de"),
                ],
                default="always",
                max_length=20,
                verbose_name="Condición",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="visibility_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visible_questions",
                to="surveys.surveyoption",
                verbose_name="Opción esperada",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="visibility_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_questions",
                to="surveys.surveyquestion",
                verbose_name="Depende de",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="visibility_value",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="Valor esperado"
            ),
        ),
    ]
