# Generated by Django 4.2.30 on 2026-07-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_survey_assigned_users_and_apply_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={
                "ordering": ["-created_date"],
                "permissions": (
                    ("publish_survey", "Puede publicar/cerrar encuestas"),
                    ("apply_all_surveys", "Puede responder todas las encuestas"),
                    (
                        "manage_survey_assignments",
                        "Puede gestionar asignación de encuestas",
                    ),
                    ("view_survey_results", "Puede ver resultados de encuestas"),
                    ("export_survey_results", "Puede exportar resultados de encuestas"),
                ),
                "verbose_name": "Encuesta",
                "verbose_name_plural": "Encuestas",
            },
        ),
    ]
