# Generated by Django 4.2.30 on 2026-07-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_survey_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='visibility_operator',
            field=models.CharField(choices=[('always', 'Siempre visible'), ('equals', 'Mostrar si es igual a'), ('not_equals', 'Mostrar si es distinto de'), ('greater_than', 'Mostrar si es mayor que'), ('less_than', 'Mostrar si es menor que')], default='always', max_length=20, verbose_name='Condición'),
        ),
    ]
