# Generated by Django 4.2.30 on 2026-07-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_surveyquestion_visibility_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='allow_other',
            field=models.BooleanField(default=False, help_text='Solo aplica a selección única o múltiple.', verbose_name='Permitir opción "Otro"'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='max_selections',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Solo aplica a selección múltiple.', null=True, verbose_name='Máximo de opciones'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo aplica a preguntas de tipo número.', max_digits=14, null=True, verbose_name='Valor máximo'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='min_selections',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Solo aplica a selección múltiple.', null=True, verbose_name='Mínimo de opciones'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo aplica a preguntas de tipo número.', max_digits=14, null=True, verbose_name='Valor mínimo'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('short_text', 'Texto corto'), ('long_text', 'Texto largo'), ('number', 'Número'), ('date', 'Fecha'), ('time', 'Hora'), ('yes_no', 'Sí/No'), ('single_choice', 'Selección única'), ('multiple_choice', 'Selección múltiple'), ('scale_5', 'Escala 1-5'), ('scale_10', 'Escala 1-10'), ('email', 'Correo'), ('phone', 'Teléfono'), ('file', 'Archivo'), ('image', 'Imagen'), ('location', 'Ubicación GPS'), ('nps', 'NPS (0-10)'), ('ranking', 'Ordenar opciones')], default='short_text', max_length=30, verbose_name='Tipo'),
        ),
    ]
