"""Campaign-level views.

Currently only the active-campaign switcher lives here — the CRUD surface
is generated by ``superadmin`` via ``apps/campaigns/sites.py``.
"""
import re

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.http import url_has_allowed_host_and_scheme
from django.views.decorators.http import require_POST

from apps.campaigns.active import clear_active_campaign, set_active_campaign
from apps.campaigns.models import Campaign

# Matches detail / edit / delete URL patterns produced by ``superadmin``:
#   /<app>/<model>/<pk>/
#   /<app>/<model>/<pk>/editar/
#   /<app>/<model>/<pk>/eliminar/
# The pk segment is stripped after a campaign switch so the user lands on
# the list view instead of a 404, which is what happens when the record is
# no longer in the new campaign's scope (``ActiveCampaignScopeMixin``).
_DETAIL_PATH_RE = re.compile(
    r"^(?P<base>/[^?#]+?)/\d+/(?:editar|eliminar|change|delete)?/?(?P<query>\?.*)?$"
)


def _safe_next(request, fallback: str) -> str:
    """Return a same-host redirect target, or the fallback.

    Uses Django's ``url_has_allowed_host_and_scheme`` instead of a hand-rolled
    prefix check because the obvious ``startswith("/") and not "//"`` rule
    misses bypasses like ``/\\evil.com/path`` — Chrome and Firefox normalize
    backslashes to slashes very early in URL parsing, turning that path into
    a protocol-relative redirect.

    Detail / edit / delete URLs are downgraded to the parent list URL: after
    a campaign switch the record they reference is usually out of scope, so
    redirecting back would 404. Stripping the pk lands the user on a useful
    page instead.
    """
    candidates = [
        request.POST.get("next"),
        request.META.get("HTTP_REFERER"),
    ]
    allowed_hosts = {request.get_host()}
    require_https = request.is_secure()
    for candidate in candidates:
        if candidate and url_has_allowed_host_and_scheme(
            candidate,
            allowed_hosts=allowed_hosts,
            require_https=require_https,
        ):
            return _downgrade_detail_url(candidate)
    return fallback


def _downgrade_detail_url(url: str) -> str:
    """Strip the ``/<pk>/[editar|eliminar]/`` tail so the user lands on the list."""
    # The regex only cares about the path; preserve scheme/host/query verbatim
    # by separating them out before matching.
    from urllib.parse import urlsplit, urlunsplit

    parts = urlsplit(url)
    path = parts.path or "/"
    match = _DETAIL_PATH_RE.match(path + (f"?{parts.query}" if parts.query else ""))
    if not match:
        return url
    new_path = match.group("base") + "/"
    return urlunsplit((parts.scheme, parts.netloc, new_path, parts.query, parts.fragment))


@require_POST
@login_required
def switch_active_campaign(request, pk: int):
    """Set the active campaign in the session.

    The queryset is implicitly scoped to the current tenant schema by
    django-tenants, so a forged id from another tenant simply 404s.
    """
    campaign = get_object_or_404(Campaign, pk=pk, is_active=True)
    set_active_campaign(request, campaign)
    messages.success(request, f"Campaña activa: {campaign}")
    return HttpResponseRedirect(_safe_next(request, reverse("home")))


@require_POST
@login_required
def clear_active_campaign_view(request):
    clear_active_campaign(request)
    messages.info(request, "Campaña activa desactivada.")
    return HttpResponseRedirect(_safe_next(request, reverse("home")))
