# Generated by Django 4.2.30 on 2026-05-07 17:02

import core.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('icon', models.CharField(default='element-12', help_text='Nombre del icono KeenIcons usado en mapas y vistas.', max_length=60, verbose_name='Icono')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tipo de publicidad',
                'verbose_name_plural': 'Tipos de publicidad',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('list_number', models.CharField(max_length=16, verbose_name='Lista')),
                ('political_organization', models.CharField(max_length=180, verbose_name='Organización política')),
                ('candidate_name', models.CharField(blank=True, max_length=180, verbose_name='Candidato')),
                ('color', models.CharField(blank=True, help_text='Hex #RRGGBB', max_length=7, verbose_name='Color')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitors', to='campaigns.campaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Competidor',
                'verbose_name_plural': 'Competidores',
                'ordering': ['campaign', 'list_number', 'political_organization'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResultOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Resultado de levantamiento',
                'verbose_name_plural': 'Resultados de levantamiento',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FieldSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('code', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Código')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud GPS')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud GPS')),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precisión GPS (m)')),
                ('location_was_manually_adjusted', models.BooleanField(default=False, verbose_name='Ubicación ajustada manualmente')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Referencia')),
                ('person_name', models.CharField(blank=True, max_length=180, verbose_name='Nombre de persona')),
                ('person_phone', models.CharField(blank=True, max_length=32, verbose_name='Teléfono')),
                ('voters_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de votantes')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('brigadier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Brigadista')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_surveys', to='campaigns.campaign', verbose_name='Campaña')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_field_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_surveys', to='locations.sector', verbose_name='Barrio / sector')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_surveys', to='locations.parish', verbose_name='Parroquia')),
                ('results', models.ManyToManyField(blank=True, related_name='field_surveys', to='field_surveys.surveyresultoption', verbose_name='Resultados')),
            ],
            options={
                'verbose_name': 'Levantamiento de campo',
                'verbose_name_plural': 'Levantamientos de campo',
                'ordering': ['-created_date'],
                'permissions': (('view_all_fieldsurvey', 'Puede ver todos los levantamientos de campo'),),
            },
        ),
        migrations.CreateModel(
            name='CompetitorAdvertisingDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('modified_user', models.CharField(editable=False, max_length=128, null=True, verbose_name='modificado por')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud GPS')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud GPS')),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precisión GPS (m)')),
                ('location_was_manually_adjusted', models.BooleanField(default=False, verbose_name='Ubicación ajustada manualmente')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Referencia')),
                ('photo', core.fields.CompressedImageField(blank=True, null=True, upload_to='field_surveys/competitor_advertising/', verbose_name='Foto')),
                ('observation', models.TextField(blank=True, verbose_name='Observación')),
                ('advertising_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitor_advertising_detections', to='field_surveys.advertisingtype', verbose_name='Tipo de publicidad')),
                ('brigadier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitor_advertising_detections', to=settings.AUTH_USER_MODEL, verbose_name='Brigadista')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitor_advertising_detections', to='campaigns.campaign', verbose_name='Campaña')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertising_detections', to='field_surveys.competitor', verbose_name='Competidor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_competitor_advertising_detections', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('field_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_advertising_detections', to='field_surveys.fieldsurvey', verbose_name='Levantamiento')),
            ],
            options={
                'verbose_name': 'Publicidad de competencia detectada',
                'verbose_name_plural': 'Publicidad de competencia detectada',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='competitor',
            constraint=models.UniqueConstraint(fields=('campaign', 'list_number', 'political_organization'), name='field_surveys_unique_competitor_by_campaign'),
        ),
    ]
