# Generated by Django 4.2.30 on 2026-05-07 17:57

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsurvey',
            name='photo',
            field=core.fields.CompressedImageField(blank=True, help_text='Opcional. Foto referencial del lugar visitado.', null=True, upload_to='field_surveys/visits/', verbose_name='Foto del lugar'),
        ),
    ]
