# Generated by Django 4.2.30 on 2026-05-05

from django.db import migrations, models
import django.db.models.deletion


SURVEY_RESULTS = [
    ("NO_ATENDIO", "No atendió"),
    ("ATENDIO", "Atendió"),
    ("APOYA", "Apoya"),
    ("INDECISO", "Indeciso"),
    ("NO_APOYA", "No apoya"),
    ("ACEPTA_PUBLICIDAD", "Acepta publicidad"),
    ("RECHAZA_PUBLICIDAD", "Rechaza publicidad"),
    ("REQUIERE_SEGUIMIENTO", "Requiere seguimiento"),
]

OWN_AD_TYPES = [
    ("AFICHE", "Afiche"),
    ("STICKER", "Sticker"),
    ("LONA", "Lona"),
    ("BANNER", "Banner"),
    ("OTRO", "Otro"),
]

COMPETITOR_AD_TYPES = [
    ("AFICHE", "Afiche"),
    ("STICKER", "Sticker"),
    ("LONA", "Lona"),
    ("BANNER", "Banner"),
    ("VALLA", "Valla"),
    ("OTRO", "Otro"),
]


def seed_catalogs(apps, schema_editor):
    SurveyResultOption = apps.get_model("field_surveys", "SurveyResultOption")
    OwnAdvertisingType = apps.get_model("field_surveys", "OwnAdvertisingType")
    CompetitorAdvertisingType = apps.get_model("field_surveys", "CompetitorAdvertisingType")

    for order, (code, name) in enumerate(SURVEY_RESULTS, start=10):
        SurveyResultOption.objects.update_or_create(
            code=code,
            defaults={"name": name, "order": order, "is_active": True},
        )
    for order, (code, name) in enumerate(OWN_AD_TYPES, start=10):
        OwnAdvertisingType.objects.update_or_create(
            code=code,
            defaults={"name": name, "order": order, "is_active": True},
        )
    for order, (code, name) in enumerate(COMPETITOR_AD_TYPES, start=10):
        CompetitorAdvertisingType.objects.update_or_create(
            code=code,
            defaults={"name": name, "order": order, "is_active": True},
        )


def migrate_existing_values(apps, schema_editor):
    FieldSurvey = apps.get_model("field_surveys", "FieldSurvey")
    OwnAdvertisingPlacement = apps.get_model("field_surveys", "OwnAdvertisingPlacement")
    CompetitorAdvertisingDetection = apps.get_model("field_surveys", "CompetitorAdvertisingDetection")
    OwnAdvertisingType = apps.get_model("field_surveys", "OwnAdvertisingType")
    CompetitorAdvertisingType = apps.get_model("field_surveys", "CompetitorAdvertisingType")
    Parish = apps.get_model("locations", "Parish")
    Sector = apps.get_model("locations", "Sector")

    parish_by_name = {p.name.lower(): p.pk for p in Parish.objects.all()}
    sector_by_name = {s.name.lower(): s.pk for s in Sector.objects.all()}
    own_type_by_code = {t.code: t.pk for t in OwnAdvertisingType.objects.all()}
    competitor_type_by_code = {t.code: t.pk for t in CompetitorAdvertisingType.objects.all()}

    for survey in FieldSurvey.objects.all():
        update_fields = []
        if getattr(survey, "parish_text", ""):
            parish_id = parish_by_name.get(survey.parish_text.lower())
            if parish_id:
                survey.parish_id = parish_id
                update_fields.append("parish")
        if getattr(survey, "neighborhood_text", ""):
            sector_id = sector_by_name.get(survey.neighborhood_text.lower())
            if sector_id:
                survey.neighborhood_id = sector_id
                update_fields.append("neighborhood")
        if update_fields:
            survey.save(update_fields=update_fields)

    for placement in OwnAdvertisingPlacement.objects.all():
        type_id = own_type_by_code.get(placement.advertising_type_legacy)
        if type_id:
            placement.advertising_type_id = type_id
            placement.save(update_fields=["advertising_type"])

    for detection in CompetitorAdvertisingDetection.objects.all():
        type_id = competitor_type_by_code.get(detection.advertising_type_legacy)
        if type_id:
            detection.advertising_type_id = type_id
            detection.save(update_fields=["advertising_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_seed_ecuador"),
        ("field_surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitorAdvertisingType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación")),
                ("created_user", models.CharField(editable=False, max_length=128, null=True, verbose_name="creado por")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="última fecha de modificación")),
                ("modified_user", models.CharField(editable=False, max_length=128, null=True, verbose_name="modificado por")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("code", models.CharField(max_length=40, unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=120, verbose_name="Nombre")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Orden")),
            ],
            options={
                "verbose_name": "Tipo de publicidad de competencia",
                "verbose_name_plural": "Tipos de publicidad de competencia",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OwnAdvertisingType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación")),
                ("created_user", models.CharField(editable=False, max_length=128, null=True, verbose_name="creado por")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="última fecha de modificación")),
                ("modified_user", models.CharField(editable=False, max_length=128, null=True, verbose_name="modificado por")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("code", models.CharField(max_length=40, unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=120, verbose_name="Nombre")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Orden")),
            ],
            options={
                "verbose_name": "Tipo de publicidad propia",
                "verbose_name_plural": "Tipos de publicidad propia",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RunPython(seed_catalogs, migrations.RunPython.noop),
        migrations.RenameField("FieldSurvey", "parish", "parish_text"),
        migrations.RenameField("FieldSurvey", "neighborhood", "neighborhood_text"),
        migrations.RenameField("OwnAdvertisingPlacement", "advertising_type", "advertising_type_legacy"),
        migrations.RenameField("CompetitorAdvertisingDetection", "advertising_type", "advertising_type_legacy"),
        migrations.AddField(
            model_name="fieldsurvey",
            name="parish",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="field_surveys", to="locations.parish", verbose_name="Parroquia"),
        ),
        migrations.AddField(
            model_name="fieldsurvey",
            name="neighborhood",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="field_surveys", to="locations.sector", verbose_name="Barrio / sector"),
        ),
        migrations.AddField(
            model_name="ownadvertisingplacement",
            name="advertising_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="own_advertising_placements", to="field_surveys.ownadvertisingtype", verbose_name="Tipo de publicidad"),
        ),
        migrations.AddField(
            model_name="competitoradvertisingdetection",
            name="advertising_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="competitor_advertising_detections", to="field_surveys.competitoradvertisingtype", verbose_name="Tipo de publicidad"),
        ),
        migrations.RunPython(migrate_existing_values, migrations.RunPython.noop),
        migrations.RemoveField("FieldSurvey", "parish_text"),
        migrations.RemoveField("FieldSurvey", "neighborhood_text"),
        migrations.RemoveField("OwnAdvertisingPlacement", "advertising_type_legacy"),
        migrations.RemoveField("CompetitorAdvertisingDetection", "advertising_type_legacy"),
        migrations.AlterField(
            model_name="ownadvertisingplacement",
            name="advertising_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="own_advertising_placements", to="field_surveys.ownadvertisingtype", verbose_name="Tipo de publicidad"),
        ),
        migrations.AlterField(
            model_name="competitoradvertisingdetection",
            name="advertising_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="competitor_advertising_detections", to="field_surveys.competitoradvertisingtype", verbose_name="Tipo de publicidad"),
        ),
    ]
