# Generated by Django 4.2.30 on 2026-05-05

from django.db import migrations, models
import django.db.models.deletion


AD_TYPES = [
    ("AFICHE", "Afiche"),
    ("STICKER", "Sticker"),
    ("LONA", "Lona"),
    ("BANNER", "Banner"),
    ("VALLA", "Valla"),
    ("OTRO", "Otro"),
]


def seed_and_migrate(apps, schema_editor):
    AdvertisingType = apps.get_model("field_surveys", "AdvertisingType")
    OwnAdvertisingType = apps.get_model("field_surveys", "OwnAdvertisingType")
    CompetitorAdvertisingType = apps.get_model("field_surveys", "CompetitorAdvertisingType")
    OwnAdvertisingPlacement = apps.get_model("field_surveys", "OwnAdvertisingPlacement")
    CompetitorAdvertisingDetection = apps.get_model("field_surveys", "CompetitorAdvertisingDetection")

    for order, (code, name) in enumerate(AD_TYPES, start=10):
        AdvertisingType.objects.update_or_create(
            code=code,
            defaults={"name": name, "order": order, "is_active": True},
        )

    by_code = {at.code: at.pk for at in AdvertisingType.objects.all()}
    own_old = {t.pk: t.code for t in OwnAdvertisingType.objects.all()}
    comp_old = {t.pk: t.code for t in CompetitorAdvertisingType.objects.all()}

    for placement in OwnAdvertisingPlacement.objects.all():
        code = own_old.get(placement.advertising_type_legacy_id)
        new_id = by_code.get(code) if code else None
        if new_id:
            placement.advertising_type_id = new_id
            placement.save(update_fields=["advertising_type"])

    for detection in CompetitorAdvertisingDetection.objects.all():
        code = comp_old.get(detection.advertising_type_legacy_id)
        new_id = by_code.get(code) if code else None
        if new_id:
            detection.advertising_type_id = new_id
            detection.save(update_fields=["advertising_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("field_surveys", "0002_catalog_models_and_location_fks"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación")),
                ("created_user", models.CharField(editable=False, max_length=128, null=True, verbose_name="creado por")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="última fecha de modificación")),
                ("modified_user", models.CharField(editable=False, max_length=128, null=True, verbose_name="modificado por")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("code", models.CharField(max_length=40, unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=120, verbose_name="Nombre")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Orden")),
            ],
            options={
                "verbose_name": "Tipo de publicidad",
                "verbose_name_plural": "Tipos de publicidad",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RenameField(
            model_name="ownadvertisingplacement",
            old_name="advertising_type",
            new_name="advertising_type_legacy",
        ),
        migrations.RenameField(
            model_name="competitoradvertisingdetection",
            old_name="advertising_type",
            new_name="advertising_type_legacy",
        ),
        migrations.AlterField(
            model_name="ownadvertisingplacement",
            name="advertising_type_legacy",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="field_surveys.ownadvertisingtype", verbose_name="Tipo de publicidad (legacy)"),
        ),
        migrations.AlterField(
            model_name="competitoradvertisingdetection",
            name="advertising_type_legacy",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="field_surveys.competitoradvertisingtype", verbose_name="Tipo de publicidad (legacy)"),
        ),
        migrations.AddField(
            model_name="ownadvertisingplacement",
            name="advertising_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="own_advertising_placements", to="field_surveys.advertisingtype", verbose_name="Tipo de publicidad"),
        ),
        migrations.AddField(
            model_name="competitoradvertisingdetection",
            name="advertising_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="competitor_advertising_detections", to="field_surveys.advertisingtype", verbose_name="Tipo de publicidad"),
        ),
        migrations.RunPython(seed_and_migrate, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="ownadvertisingplacement",
            name="advertising_type_legacy",
        ),
        migrations.RemoveField(
            model_name="competitoradvertisingdetection",
            name="advertising_type_legacy",
        ),
        migrations.AlterField(
            model_name="ownadvertisingplacement",
            name="advertising_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="own_advertising_placements", to="field_surveys.advertisingtype", verbose_name="Tipo de publicidad"),
        ),
        migrations.AlterField(
            model_name="competitoradvertisingdetection",
            name="advertising_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="competitor_advertising_detections", to="field_surveys.advertisingtype", verbose_name="Tipo de publicidad"),
        ),
        migrations.DeleteModel(name="OwnAdvertisingType"),
        migrations.DeleteModel(name="CompetitorAdvertisingType"),
    ]
