# Generated by Django 4.2.30 on 2026-05-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_surveys', '0002_fieldsurvey_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitoradvertisingdetection',
            name='address',
        ),
        migrations.RemoveField(
            model_name='competitoradvertisingdetection',
            name='reference',
        ),
    ]
