# Generated by Django 4.2.30 on 2026-05-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_surveys', '0003_remove_competitoradvertisingdetection_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldsurvey',
            name='address',
        ),
        migrations.RemoveField(
            model_name='fieldsurvey',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='fieldsurvey',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='fieldsurvey',
            name='reference',
        ),
    ]
