# Generated by Django 4.2.30 on 2026-05-06 18:00

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_surveys', '0003_unify_advertising_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitoradvertisingdetection',
            name='photo',
            field=core.fields.CompressedImageField(blank=True, null=True, upload_to='field_surveys/competitor_advertising/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='ownadvertisingplacement',
            name='photo',
            field=core.fields.CompressedImageField(upload_to='field_surveys/own_advertising/', verbose_name='Foto de evidencia'),
        ),
    ]
