# Generated by Django 4.2.30 on 2026-05-08 20:15

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_surveys', '0005_split_survey_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='color',
            field=core.fields.ColorField(blank=True, help_text='Hex #RRGGBB', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='surveyadvertisingresponse',
            name='color',
            field=core.fields.ColorField(blank=True, help_text='Hex #RRGGBB usado en mapas, dashboard y badges.', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='surveysupportlevel',
            name='color',
            field=core.fields.ColorField(blank=True, help_text='Hex #RRGGBB usado en mapas, dashboard y badges.', max_length=7, verbose_name='Color'),
        ),
    ]
