# Generated by Django 4.2.30 on 2026-05-08 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_surveys', '0006_alter_competitor_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingtype',
            name='icon',
            field=models.CharField(default='element-12', help_text='Nombre del icono KeenIcons usado en mapas y vistas.', max_length=60, validators=[django.core.validators.RegexValidator(code='invalid_icon_name', message="Usa el nombre del ícono Keenicons en minúsculas, sin el prefijo 'ki-' (ej. 'calendar-tick').", regex='^[a-z0-9][a-z0-9-]*$')], verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='competitoradvertisingdetection',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90, message='La latitud debe estar entre -90 y 90.'), django.core.validators.MaxValueValidator(90, message='La latitud debe estar entre -90 y 90.')], verbose_name='Latitud GPS'),
        ),
        migrations.AlterField(
            model_name='competitoradvertisingdetection',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180, message='La longitud debe estar entre -180 y 180.'), django.core.validators.MaxValueValidator(180, message='La longitud debe estar entre -180 y 180.')], verbose_name='Longitud GPS'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90, message='La latitud debe estar entre -90 y 90.'), django.core.validators.MaxValueValidator(90, message='La latitud debe estar entre -90 y 90.')], verbose_name='Latitud GPS'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180, message='La longitud debe estar entre -180 y 180.'), django.core.validators.MaxValueValidator(180, message='La longitud debe estar entre -180 y 180.')], verbose_name='Longitud GPS'),
        ),
    ]
