# Generated by Django 4.2.30 on 2026-06-12 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_surveys', '0007_alter_advertisingtype_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='acronym',
            field=models.CharField(blank=True, help_text='Letras o números (máx. 3) mostrados en el pin del mapa; si se omite se usa la lista.', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{1,3}$', 'Usa solo letras o números (máximo 3 caracteres).')], verbose_name='Acrónimo'),
        ),
    ]
