# Generated by Django 4.2.30 on 2026-05-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'username'], 'permissions': (('view_profile', 'Ver perfil de usuario'), ('change_full_own_profile', 'Puede editar la configuración completa de su propio perfil (email, teléfono, biografía)')), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
