# Generated by Django 4.2.30 on 2026-05-06 18:00

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=core.fields.CompressedImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
